# Site settings
title:       Math 126 Journal
email:       ll29@uw.edu
author:      Li Lin
description: ""
baseurl:     "/MATH126"
url:         "https://linl33.github.io"
date_format: "%b %-d, %Y"

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax:       false
extended_fonts:       false
enable_anchorjs:      false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
