# Site settings
title:       Math 126 Journal
email:       ll29@uw.edu
author:      Li Lin
description: ""
baseurl:     "/MATH126"
url:         "https://linl33.github.io"
date_format: "%b %-d, %Y"

# Optional features
animated:             false
enable_mathjax:       true
extended_fonts:       true
enable_anchorjs:      false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     5
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
